services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  medication:
    build: .
    depends_on:
      - dynamodb
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
