services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  init-dynamodb:
    image: amazon/aws-cli
    depends_on:
      - dynamodb
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    entrypoint: [ "sh", "-c", "
      for i in $$(seq 1 3); do aws dynamodb create-table
        --table-name medication
        --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S
        --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE
        --billing-mode PAY_PER_REQUEST
        --endpoint-url http://dynamodb:8000
        --region us-west-2 && break || sleep 1;
      done && echo Table Created" ]

  medication:
    build: .
    depends_on:
      - init-dynamodb
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=us-west-2
      - MED_DYNAMO_ENDPOINT=http://dynamodb:8000
