name: Make
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  LintTest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@main

    # Test code
    - name: Lint
      run: make lint

    - name: Test
      run: make test
