name: Make
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@main

    - name: Lint
      run: make lint

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Test
        run: make test
